version: '3.7'

services:
  stub:
    build:
      context: ../
      dockerfile: build/Dockerfile
      args:
        - LDFLAGS=$LDFLAGS
        - CONFIG_FILE_NAME=$CONFIG_FILE_NAME
    container_name: stub
    restart: on-failure
    ports:
      - '8888:8888'
    expose:
      - 8888
    volumes:
      - ./logs/:/tmp/
