version: '3.7'

services:
  integration_tests:
    build: ../test
    container_name: stub_test_bdd
    command: 'true'
    environment:
      TESTS_HTTP_HOST: 'http://stub:8888'
      WAIT_HOSTS: stub:8888
    depends_on:
      - stub
    links:
      - stub

  stub:
    build:
      context: ../
      dockerfile: build/Dockerfile
      args:
        - LDFLAGS=$LDFLAGS
        - CONFIG_FILE_NAME=$CONFIG_FILE_NAME
    container_name: stub_test
    restart: on-failure
    ports:
      - '8888:8888'
    expose:
      - 8888
    volumes:
      - ./logs/:/tmp/
